apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: indomarco-tms
  name: tms-engine-deployment
  labels:
    name: tms-engine-deployment
spec:
  selector:
    matchLabels:
      app: tms-apps
  template:
    metadata:
      labels:
        app: tms-apps
    spec:
      containers:
        - name: indomarco-tms-engine
          image: 369693/tms-best:96f7c7e9d2c8cf6c910771fbb51733da6642a914
          volumeMounts:
            - mountPath: /opt/telegram
              name: telegram-data
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1500m"
          ports:
            - containerPort: 8183
      volumes:
        - name: telegram-data
          nfs:
            server: 172.18.185.110
            path: /srv/nfs/storage/
