apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: indomarco-tms
  name: tms-engine-deployment
  labels:
    name: tms-engine-deployment
spec:
  selector:
    matchLabels:
      app: tms-apps
  template:
    metadata:
      labels:
        app: tms-apps
    spec:
      containers:
        - name: indomarco-tms-engine
          image: 369693/indomarco-tms:prod-1.0
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1500m"
          ports:
            - containerPort: 8183
      